name: build

on:
  push:
    branches: [master]
  workflow_dispatch: {}
  schedule:
    - cron: '30 23 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate package index
      env:
        GITHUB_TOKEN: ${{ secrets.GITHU_TOKEN }}
      run: python3 main.py
    - name: Deploy to GitHub Pages
      if: "github.ref == 'refs/heads/master'"
      run: |
        CINFO="$(git log -1 --pretty="[%h] %an: %s")"
        cd output
        git init --quiet
        : > .nojekyll
        git remote add origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        git fetch --depth=1 origin gh-pages
        git reset --soft FETCH_HEAD
        git add --all
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "Auto deploy from GitHub Actions build ${GITHUB_RUN_NUMBER}" \
          -m "$CINFO"
        git push origin +HEAD:gh-pages
